services:
  - type: web
    name: agriguru
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      cd frontend && npm ci && npm run build && cd ..
    startCommand: gunicorn -w 2 -k gthread --threads 4 --timeout 120 -b 0.0.0.0:$PORT wsgi:application
    autoDeploy: true
    envVars:
      - key: PYTHONPATH
        value: backend
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        sync: false