services:
  - type: web
    name: agriguru-backend
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install -r backend/requirements.txt
    startCommand: gunicorn -w 2 -k gthread --threads 4 --timeout 120 -b 0.0.0.0:$PORT wsgi:application
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONPATH
        value: backend
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: FRONTEND_ORIGIN
        fromService:
          name: agriguru-frontend
          type: web
          property: url

  - type: web
    name: agriguru-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_BASE
        fromService:
          name: agriguru-backend
          type: web
          property: url